# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cef7da2705aec251562807b34c1e524b"
name = "My Gold Rate"
handle = "my-gold-rate"
application_url = "https://reseller-forming-delivers-ni.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "thetelarana.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://reseller-forming-delivers-ni.trycloudflare.com/auth/callback",
  "https://reseller-forming-delivers-ni.trycloudflare.com/auth/shopify/callback",
  "https://reseller-forming-delivers-ni.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
