# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fa18300b7d1809fb77b197eb9fafa5d1"
name = "Gold Product Price"
handle = "gold-product-price"
application_url = "https://marilyn-directory-loading-sin.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "hellowebx.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://marilyn-directory-loading-sin.trycloudflare.com/auth/callback",
  "https://marilyn-directory-loading-sin.trycloudflare.com/auth/shopify/callback",
  "https://marilyn-directory-loading-sin.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
